### PR TITLE
add configs for sequelize-cli reading from existing env files

### PR DESCRIPTION
**Pull request by sheershoff**
Needed to allow running `sequelize db:migrate`, etc

### CODE REVIEW

**Comment by jpotts18** [comment]
I like this addition! We will need documentation in order for people to know how to use it. Could you add a couple lines showing what a migration does or where users can learn more?

**Comment by sheershoff** [comment]
Added some info on sequelize-cli. This also closes #54 I believe. I think concepts of migrations and seeders for DB are beyond the readme, still, it is a good occasion to learn if one is interested.

**Comment by jpotts18** [comment]
@chaudhryjunaid any reservations to a merge?

**Comment by chaudhryjunaid** [comment]
looks great! LGTM!

**Comment by jpotts18** [comment]
No updates or issue resolutions planned.

**Pull request closed without merging**
